default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog_development
  username: spp_user
  password: admin

test:
  <<: *default
  database: blog_test
  username: spp_user
  password: admin

production:
  <<: *default
  database: blog_production
  username: spp_user
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
