# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59430ea77921c9c933b66e413f93e93400ae3f39280fe9d61c668a2467316e70619ab86b28e8130ad24d8a2b6fe7d1cd871b98dfdf70939b2102f0181a703270

test:
  secret_key_base: 04c15eea90a40e7649025786ba0913cb68f4771f51d1c5f5f4da610f2bf3b4cb849fbd29cdc7915503c169e9b71fef4ebf4da430fe915a665f4b59a9a60ba30a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
